from fpdf import FPDF
from tkinter import *
from tkinter import filedialog


muT = "\u03BC"

def curvanormal(nocolas, alfa, mp, mm, n, desvest,Zinf,Zsup,zp,pvalor):
    alpha2 = str(alfa*100)
    nT = str(n)

    #P : portrait (vertical)
    #L : landscape (horizontal)
    #A4 : 210x297mm

    pdf = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf.add_page()
    

    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)

    #LINEA
    pdf.line(25,70,190,70)
    pdf.line(63,25,63,70)

    #TEXTO
    pdf.set_font('Arial','',14)
    pdf.text(x = 65,y = 35, txt = 'Analisis Probabilistico')
    pdf.text(x = 65,y = 40, txt = 'Ing. Manuel Eduardo Alvarez Ruiz')
    pdf.text(x = 65,y = 45, txt = 'Proyecto Programa prueba de hipotesis')
    pdf.text(x = 65,y = 50, txt = 'Eduardo Rubén Cruz Sánchez         202146471')
    pdf.text(x = 65,y = 55, txt = 'Nery José Galdámez Aristondo        202140502')
    pdf.text(x = 65,y = 60, txt = 'Ramiro André Chacón Castañeda    201940859')
    pdf.text(x = 65,y = 65, txt = 'Kenat Jesiel Pérez Lucas                  202040366')

    #Hoja del problema
    pdf.text(x = 30,y = 80, txt = 'Paso 1: Formulacion de hipotesis')
    if(nocolas == 1):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu = ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu != ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: entre los valores de Zcrítico (')
        pdf.text(x = 140,y = 225, txt = str(Zinf))
        pdf.text(x = 155,y = 225, txt = ',')
        pdf.text(x = 160,y = 225, txt = str(Zsup))
        pdf.text(x = 170,y = 225, txt = ')')
        pdf.text(x = 30,y = 230, txt = 'Área de rechazo: a la izquierda de Zc1 = ')
        pdf.text(x = 120,y = 230, txt = str(Zinf))
        pdf.text(x = 30,y = 235, txt = 'Area de rechazo: a la derecha de Zc2 = ')
        pdf.text(x = 120,y = 235, txt = str(Zsup))
    if(nocolas == 2):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu >= ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu < ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: a la derecha del valor de Zcrítico = ')
        pdf.text(x = 155,y = 225, txt = str(Zinf))
    if(nocolas == 3):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu <= ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu > ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: a la izquierda del valor de Zcrítico = ')
        pdf.text(x = 155,y = 225, txt = str(Zsup))
    pdf.text(x = 30,y = 95, txt = 'Paso 2: Nivel de significancia alpha')
    pdf.text(x = 30,y = 100, txt = 'alpha = ')
    pdf.text(x = 47,y = 100, txt = str(alfa))
    pdf.text(x = 57,y = 100, txt = ' = ')
    pdf.text(x = 63,y = 100, txt = alpha2)
    pdf.text(x = 70,y = 100, txt = '%')
    pdf.text(x = 30,y = 105, txt = 'Paso 3: Estadistico de prueba')
    pdf.image('img/Estadistico_curvanormal.png',x = 30,y = 110,w = 40, h = 20)


    #IMAGEN
    pdf.image('img/logotipo-cunori-transparente.png',x = 27,y = 29,w = 33, h = 33)

    '''#-------------------------------------------------PAGINA 2------------------------------------------------'''
    pdf.add_page()
    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)
    pdf.text(x = 30,y = 35, txt = 'Paso 5: Prueba del estadistico')
    pdf.image('img/Estadistico_curvanormal.png',x = 30,y = 40,w = 40, h = 20)
    pdf.text(x = 70,y = 50, txt = ' =')
    pdf.text(x = 75,y = 50, txt = '(')
    pdf.text(x = 80,y = 50, txt = str(mm))
    pdf.text(x = 95,y = 50, txt = '-')
    pdf.text(x = 100,y = 50, txt = str(mp))
    pdf.text(x = 110,y = 50, txt = ')/(')
    pdf.text(x = 115,y = 50, txt = str(desvest))
    pdf.text(x = 130,y = 50, txt = '/raiz(')
    pdf.text(x = 140,y = 50, txt = nT)
    pdf.text(x = 155,y = 50, txt = ')) =')
    pdf.text(x = 165,y = 50, txt = str(zp))
    if(nocolas == 1):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf and zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 125,y = 185, txt = str(Zinf))
            pdf.text(x = 140,y = 185, txt = ',')
            pdf.text(x = 145,y = 185, txt = str(Zsup))
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 130,y = 185, txt = str(Zinf))
            pdf.text(x = 145,y = 185, txt = ',')
            pdf.text(x = 150,y = 185, txt = str(Zsup))
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 2):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que Zcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = ' es menor que Zcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 3):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es menor que Zcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que Zcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))

    pdf.image('img/grafica2.jpg',x = 40,y = 80,w = 130, h = 80)
    archivo = filedialog.asksaveasfilename()
    print(archivo)
    pdf.output(archivo+".pdf")
    

def tstudent(nocolas, alfa, mp, mm, n, desvest,Zinf,Zsup,zp,pvalor):
    print('entrada a tstudent')
    gl = str(n-1)
    alpha2 = str(alfa*100)

    #P : portrait (vertical)
    #L : landscape (horizontal)
    #A4 : 210x297mm

    pdf = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf.add_page()
    

    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)

    #LINEA
    pdf.line(25,70,190,70)
    pdf.line(63,25,63,70)

    #TEXTO
    pdf.set_font('Arial','',14)
    pdf.text(x = 65,y = 35, txt = 'Analisis Probabilistico')
    pdf.text(x = 65,y = 40, txt = 'Ing. Manuel Eduardo Alvarez Ruiz')
    pdf.text(x = 65,y = 45, txt = 'Proyecto Programa prueba de hipotesis')
    pdf.text(x = 65,y = 50, txt = 'Eduardo Rubén Cruz Sánchez         202146471')
    pdf.text(x = 65,y = 55, txt = 'Nery José Galdámez Aristondo        202140502')
    pdf.text(x = 65,y = 60, txt = 'Ramiro André Chacón Castañeda    201940859')
    pdf.text(x = 65,y = 65, txt = 'Kenat Jesiel Pérez Lucas                  202040366')

    #Hoja del problema
    pdf.text(x = 30,y = 80, txt = 'Paso 1: Formulacion de hipotesis')
    pdf.text(x = 30,y = 140, txt = 'Grados de libertad g.l = muestra(n) - 1 = ')
    pdf.text(x = 120,y = 140, txt = str(n))
    pdf.text(x = 130,y = 140, txt = ' - 1 =')
    pdf.text(x = 145,y = 140, txt = gl)
    if(nocolas == 1):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu = ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu != ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: entre los valores de tcrítico (')
        pdf.text(x = 140,y = 230, txt = str(Zinf))
        pdf.text(x = 156,y = 230, txt = ',')
        pdf.text(x = 160,y = 230, txt = str(Zsup))
        pdf.text(x = 180,y = 230, txt = ')')
        pdf.text(x = 30,y = 235, txt = 'Área de rechazo: a la izquierda de tc1 = ')
        pdf.text(x = 120,y = 235, txt = str(Zinf))
        pdf.text(x = 30,y = 240, txt = 'Area de rechazo: a la derecha de tc2 = ')
        pdf.text(x = 120,y = 240, txt = str(Zsup))
    if(nocolas == 2):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu >= ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu < ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: a la derecha del valor de tcrítico = ')
        pdf.text(x = 155,y = 230, txt = str(Zinf))
    if(nocolas == 3):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu <= ')
        pdf.text(x = 53,y = 85,txt = str(mp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu > ')
        pdf.text(x = 53,y = 90,txt = str(mp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: a la izquierda del valor de tcrítico = ')
        pdf.text(x = 155,y = 230, txt = str(Zsup))
    pdf.text(x = 30,y = 95, txt = 'Paso 2: Nivel de significancia alpha')
    pdf.text(x = 30,y = 100, txt = 'alpha = ')
    pdf.text(x = 47,y = 100, txt = str(alfa))
    pdf.text(x = 57,y = 100, txt = ' = ')
    pdf.text(x = 63,y = 100, txt = alpha2)
    pdf.text(x = 70,y = 100, txt = '%')
    pdf.text(x = 30,y = 105, txt = 'Paso 3: Estadistico de prueba')
    pdf.image('img/Estadistico_tstudent.png',x = 30,y = 110,w = 40, h = 20)


    #IMAGEN
    pdf.image('img/logotipo-cunori-transparente.png',x = 27,y = 29,w = 33, h = 33)

    '''#-------------------------------------------------PAGINA 2------------------------------------------------'''
    pdf.add_page()
    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)
    pdf.text(x = 30,y = 35, txt = 'Paso 5: Prueba del estadistico')
    pdf.image('img/Estadistico_tstudent.png',x = 30,y = 40,w = 40, h = 20)
    pdf.text(x = 70,y = 50, txt = ' =')
    pdf.text(x = 75,y = 50, txt = '(')
    pdf.text(x = 80,y = 50, txt = str(mm))
    pdf.text(x = 95,y = 50, txt = '-')
    pdf.text(x = 100,y = 50, txt = str(mp))
    pdf.text(x = 110,y = 50, txt = ')/(')
    pdf.text(x = 115,y = 50, txt = str(desvest))
    pdf.text(x = 130,y = 50, txt = '/raiz(')
    pdf.text(x = 140,y = 50, txt = str(n))
    pdf.text(x = 155,y = 50, txt = ')) =')
    pdf.text(x = 165,y = 50, txt = str(zp))
    if(nocolas == 1):
        '''
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        '''
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf and zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que tp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de tcrítico (')
            pdf.text(x = 125,y = 185, txt = str(Zinf))
            pdf.text(x = 150,y = 185, txt = ',')
            pdf.text(x = 145,y = 185, txt = str(Zsup))
            pdf.text(x = 165,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que tp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de tcrítico (')
            pdf.text(x = 130,y = 185, txt = str(Zinf))
            pdf.text(x = 147,y = 185, txt = ',')
            pdf.text(x = 150,y = 185, txt = str(Zsup))
            pdf.text(x = 165,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 2):
        '''
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        '''
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que Zcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que tp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = ' es menor que tcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 3):
        '''
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        '''
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que tp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es menor que tcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que tp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que tcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))

    pdf.image('img/grafica2.jpg',x = 40,y = 80,w = 130, h = 80)
    archivo = filedialog.asksaveasfilename()
    print(archivo)
    pdf.output(archivo+".pdf")


def propmuestral(nocolas, alfa, pm, pp, n,Zinf,Zsup,q,zp,pvalor):
    alpha2 = str(alfa*100)

    #P : portrait (vertical)
    #L : landscape (horizontal)
    #A4 : 210x297mm

    pdf = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf.add_page()
    

    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)

    #LINEA
    pdf.line(25,70,190,70)
    pdf.line(63,25,63,70)

    #TEXTO
    pdf.set_font('Arial','',14)
    pdf.text(x = 65,y = 35, txt = 'Analisis Probabilistico')
    pdf.text(x = 65,y = 40, txt = 'Ing. Manuel Eduardo Alvarez Ruiz')
    pdf.text(x = 65,y = 45, txt = 'Proyecto Programa prueba de hipotesis')
    pdf.text(x = 65,y = 50, txt = 'Eduardo Rubén Cruz Sánchez         202146471')
    pdf.text(x = 65,y = 55, txt = 'Nery José Galdámez Aristondo        202140502')
    pdf.text(x = 65,y = 60, txt = 'Ramiro André Chacón Castañeda    201940859')
    pdf.text(x = 65,y = 65, txt = 'Kenat Jesiel Pérez Lucas                  202040366')

    #Hoja del problema
    pdf.text(x = 30,y = 80, txt = 'Paso 1: Formulacion de hipotesis')
    if(nocolas == 1):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu = ')
        pdf.text(x = 53,y = 85,txt = str(pp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu != ')
        pdf.text(x = 53,y = 90,txt = str(pp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: entre los valores de Zcrítico (')
        pdf.text(x = 140,y = 225, txt = str(Zinf))
        pdf.text(x = 156,y = 225, txt = ',')
        pdf.text(x = 160,y = 225, txt = str(Zsup))
        pdf.text(x = 180,y = 225, txt = ')')
        pdf.text(x = 30,y = 230, txt = 'Área de rechazo: a la izquierda de Zc1 = ')
        pdf.text(x = 120,y = 230, txt = str(Zinf))
        pdf.text(x = 30,y = 235, txt = 'Area de rechazo: a la derecha de Zc2 = ')
        pdf.text(x = 120,y = 235, txt = str(Zsup))
    if(nocolas == 2):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu >= ')
        pdf.text(x = 53,y = 85,txt = str(pp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu < ')
        pdf.text(x = 53,y = 90,txt = str(pp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: a la derecha del valor de Zc = ')
        pdf.text(x = 155,y = 225, txt = str(Zinf))
    if(nocolas == 3):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu <= ')
        pdf.text(x = 53,y = 85,txt = str(pp))
        pdf.text(x = 30,y = 90, txt = 'Ho: mu > ')
        pdf.text(x = 53,y = 90,txt = str(pp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: a la izquierda del valor de Zc = ')
        pdf.text(x = 155,y = 225, txt = str(Zsup))
    pdf.text(x = 30,y = 95, txt = 'Paso 2: Nivel de significancia alpha')
    pdf.text(x = 30,y = 100, txt = 'alpha = ')
    pdf.text(x = 47,y = 100, txt = str(alfa))
    pdf.text(x = 57,y = 100, txt = ' = ')
    pdf.text(x = 63,y = 100, txt = alpha2)
    pdf.text(x = 70,y = 100, txt = '%')
    pdf.text(x = 30,y = 105, txt = 'Paso 3: Estadistico de prueba')
    pdf.image('img/Estadistico_proporciones.png',x = 30,y = 110,w = 40, h = 20)


    #IMAGEN
    pdf.image('img/logotipo-cunori-transparente.png',x = 27,y = 29,w = 33, h = 33)

    '''#-------------------------------------------------PAGINA 2------------------------------------------------'''
    pdf.add_page()
    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)
    pdf.text(x = 30,y = 35, txt = 'Paso 5: Prueba del estadistico')
    pdf.image('img/Estadistico_proporciones.png',x = 30,y = 40,w = 40, h = 20)
    pdf.text(x = 70,y = 50, txt = ' =')
    pdf.text(x = 75,y = 50, txt = '(')
    pdf.text(x = 80,y = 50, txt = str(pm))
    pdf.text(x = 95,y = 50, txt = '-')
    pdf.text(x = 100,y = 50, txt = str(pp))
    pdf.text(x = 115,y = 50, txt = ')/raiz(')
    pdf.text(x = 128,y = 50, txt = str(pp))
    pdf.text(x = 135,y = 50, txt = '*')
    pdf.text(x = 137,y = 50, txt = str(q))
    pdf.text(x = 145,y = 50, txt = '/')
    pdf.text(x = 147,y = 50, txt = str(n))
    pdf.text(x = 155,y = 50, txt = '    ) =')
    pdf.text(x = 170,y = 50, txt = str(zp))
    if(nocolas == 1):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf and zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 125,y = 185, txt = str(Zinf))
            pdf.text(x = 150,y = 185, txt = ',')
            pdf.text(x = 145,y = 185, txt = str(Zsup))
            pdf.text(x = 165,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de tcrítico (')
            pdf.text(x = 130,y = 185, txt = str(Zinf))
            pdf.text(x = 147,y = 185, txt = ',')
            pdf.text(x = 150,y = 185, txt = str(Zsup))
            pdf.text(x = 165,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 2):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que Zcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = ' es menor que Zcrítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 3):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(zp))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es menor que Zcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = str(zp))
            pdf.text(x = 30,y = 185, txt = 'es mayor que Zcrítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))

    pdf.image('img/grafica2.jpg',x = 40,y = 80,w = 130, h = 80)
    archivo = filedialog.asksaveasfilename()
    print(archivo)
    pdf.output(archivo+".pdf")

def chicuadrado(nocolas, alfa, varm, n,Zinf,Zsup,varp,x2,pvalor):
    gl = str(n-1)
    alpha2 = str(alfa*100)

    #P : portrait (vertical)
    #L : landscape (horizontal)
    #A4 : 210x297mm

    pdf = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf.add_page()
    

    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)

    #LINEA
    pdf.line(25,70,190,70)
    pdf.line(63,25,63,70)

    #TEXTO
    pdf.set_font('Arial','',14)
    pdf.text(x = 65,y = 35, txt = 'Analisis Probabilistico')
    pdf.text(x = 65,y = 40, txt = 'Ing. Manuel Eduardo Alvarez Ruiz')
    pdf.text(x = 65,y = 45, txt = 'Proyecto Programa prueba de hipotesis')
    pdf.text(x = 65,y = 50, txt = 'Eduardo Rubén Cruz Sánchez         202146471')
    pdf.text(x = 65,y = 55, txt = 'Nery José Galdámez Aristondo        202140502')
    pdf.text(x = 65,y = 60, txt = 'Ramiro André Chacón Castañeda    201940859')
    pdf.text(x = 65,y = 65, txt = 'Kenat Jesiel Pérez Lucas                  202040366')

    #Hoja del problema
    pdf.text(x = 30,y = 80, txt = 'Paso 1: Formulacion de hipotesis')
    pdf.text(x = 30,y = 140, txt = 'Grados de libertad g.l = muestra(n) - 1 = ')
    pdf.text(x = 120,y = 140, txt = str(n))
    pdf.text(x = 130,y = 140, txt = ' - 1 =')
    pdf.text(x = 145,y = 140, txt = gl)
    if(nocolas == 1):
        pdf.text(x = 30,y = 85, txt = 'Ho: x^2 = ')
        pdf.text(x = 53,y = 85,txt = str(varp))
        pdf.text(x = 30,y = 90, txt = 'Ho: x^2 != ')
        pdf.text(x = 53,y = 90,txt = str(varp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: entre los valores de X^2crítico (')
        pdf.text(x = 145,y = 230, txt = str(Zinf))
        pdf.text(x = 161,y = 230, txt = ',')
        pdf.text(x = 166,y = 230, txt = str(Zsup))
        pdf.text(x = 186,y = 230, txt = ')')
        pdf.text(x = 30,y = 235, txt = 'Área de rechazo: a la izquierda de X^2c1 = ')
        pdf.text(x = 125,y = 235, txt = str(Zinf))
        pdf.text(x = 30,y = 240, txt = 'Area de rechazo: a la derecha de X^2c2 = ')
        pdf.text(x = 125,y = 240, txt = str(Zsup))
    if(nocolas == 2):
        pdf.text(x = 30,y = 85, txt = 'Ho: x^2 >= ')
        pdf.text(x = 53,y = 85,txt = str(varp))
        pdf.text(x = 30,y = 90, txt = 'Ho: x^2 < ')
        pdf.text(x = 53,y = 90,txt = str(varp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: a la derecha del valor de X^2crítico = ')
        pdf.text(x = 155,y = 230, txt = str(Zinf))
    if(nocolas == 3):
        pdf.text(x = 30,y = 85, txt = 'Ho: x^2 <= ')
        pdf.text(x = 53,y = 85,txt = str(varp))
        pdf.text(x = 30,y = 90, txt = 'Ho: x^2 > ')
        pdf.text(x = 53,y = 90,txt = str(varp))
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 145,w = 130, h = 80)
        pdf.text(x = 30,y = 230, txt = 'Área de no rechazo: a la izquierda del valor de X^2crítico = ')
        pdf.text(x = 155,y = 230, txt = str(Zsup))
    pdf.text(x = 30,y = 95, txt = 'Paso 2: Nivel de significancia alpha')
    pdf.text(x = 30,y = 100, txt = 'alpha = ')
    pdf.text(x = 47,y = 100, txt = str(alfa))
    pdf.text(x = 57,y = 100, txt = ' = ')
    pdf.text(x = 63,y = 100, txt = alpha2)
    pdf.text(x = 70,y = 100, txt = '%')
    pdf.text(x = 30,y = 105, txt = 'Paso 3: Estadistico de prueba')
    pdf.image('img/Estadistico_chicuadrado.png',x = 30,y = 110,w = 40, h = 20)


    #IMAGEN
    pdf.image('img/logotipo-cunori-transparente.png',x = 27,y = 29,w = 33, h = 33)

    '''#-------------------------------------------------PAGINA 2------------------------------------------------'''
    pdf.add_page()
    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)
    pdf.text(x = 30,y = 35, txt = 'Paso 5: Prueba del estadistico')
    pdf.image('img/Estadistico_chicuadrado.png',x = 30,y = 40,w = 40, h = 20)
    pdf.text(x = 70,y = 50, txt = ' =')
    pdf.text(x = 75,y = 50, txt = '(')
    pdf.text(x = 80,y = 50, txt = str(n))
    pdf.text(x = 90,y = 50, txt = '- 1)(')
    pdf.text(x = 100,y = 50, txt = str(varm))
    pdf.text(x = 115,y = 50, txt = '/')
    pdf.text(x = 117,y = 50, txt = str(varp))
    pdf.text(x = 130,y = 50, txt = ') =')
    pdf.text(x = 140,y = 50, txt = str(x2))
    if(nocolas == 1):
        '''
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(x2))
        pdf.text(x = 95,y = 70, txt = ')')
        '''
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(x2>Zinf and x2<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 150,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de X^2crítico (')
            pdf.text(x = 130,y = 185, txt = str(Zinf))
            pdf.text(x = 145,y = 185, txt = ',')
            pdf.text(x = 147,y = 185, txt = str(Zsup))
            pdf.text(x = 170,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 142,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de X^2crítico (')
            pdf.text(x = 135,y = 185, txt = str(Zinf))
            pdf.text(x = 153,y = 185, txt = ',')
            pdf.text(x = 157,y = 185, txt = str(Zsup))
            pdf.text(x = 175,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 2):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(x2))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(x2>Zinf):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 142,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = 'es mayor que X^2crítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 140,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = ' es menor que X^2crítico = ')
            pdf.text(x = 85,y = 185, txt = str(Zinf))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
    if(nocolas == 3):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 0.500 - p(Zp)')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 0.500 - p(')
        pdf.text(x = 75,y = 70, txt = str(x2))
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = str(pvalor))
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(x2<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 142,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = 'es menor que X^2crítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que X^2p = ')
            pdf.text(x = 140,y = 180, txt = str(x2))
            pdf.text(x = 30,y = 185, txt = 'es mayor que X^2crítico =')
            pdf.text(x = 85,y = 185, txt = str(Zsup))
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = str(pvalor))
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = str(alfa))

    pdf.image('img/grafica2.jpg',x = 40,y = 80,w = 130, h = 80)
    archivo = filedialog.asksaveasfilename()
    print(archivo)
    pdf.output(archivo+".pdf")