from fpdf import FPDF
from tkinter import *


muT = "\u03BC"

def imprimir1(nocolas, alfa, mp, mm, n, desvest,Zinf,Zsup,zp,pvalor):
    colas = int(nocolas)
    medp = str(mp)
    alpha = str(alfa)
    alpha2 = str(alfa*100)
    z_critico_inferior = str(Zinf)
    z_critico_superior = str(Zsup)
    mmT = str(mm)
    mpT = str(mp)
    nT = str(n)
    desvestT = str(desvest)
    zpT = str(zp)
    pvalorT = str(pvalor)

    #P : portrait (vertical)
    #L : landscape (horizontal)
    #A4 : 210x297mm

    pdf = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf2 = FPDF(orientation = 'P',unit = 'mm', format = 'A4')
    pdf.add_page()
    

    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)

    #LINEA
    pdf.line(25,70,190,70)
    pdf.line(63,25,63,70)

    #TEXTO
    pdf.set_font('Arial','',14)
    pdf.text(x = 65,y = 35, txt = 'Analisis Probabilistico')
    pdf.text(x = 65,y = 40, txt = 'Ing. Manuel Eduardo Alvarez Ruiz')
    pdf.text(x = 65,y = 45, txt = 'Proyecto Programa prueba de hipotesis')
    pdf.text(x = 65,y = 50, txt = 'Eduardo Rubén Cruz Sánchez         202146471')
    pdf.text(x = 65,y = 55, txt = 'Nery José Galdámez Aristondo        202140502')
    pdf.text(x = 65,y = 60, txt = 'Ramiro André Chacón Castañeda    201940859')
    pdf.text(x = 65,y = 65, txt = 'Kenat Jesiel Pérez Lucas                  202040366')

    #Hoja del problema
    pdf.text(x = 30,y = 80, txt = 'Paso 1: Formulacion de hipotesis')
    if(colas == 1):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu = ')
        pdf.text(x = 53,y = 85,txt = medp)
        pdf.text(x = 30,y = 90, txt = 'Ho: mu != ')
        pdf.text(x = 53,y = 90,txt = medp)
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: entre los valores de Zcrítico (')
        pdf.text(x = 140,y = 225, txt = z_critico_inferior)
        pdf.text(x = 155,y = 225, txt = ',')
        pdf.text(x = 160,y = 225, txt = z_critico_superior)
        pdf.text(x = 170,y = 225, txt = ')')
        pdf.text(x = 30,y = 230, txt = 'Área de rechazo: a la izquierda de Zc1 = ')
        pdf.text(x = 120,y = 230, txt = z_critico_inferior)
        pdf.text(x = 30,y = 235, txt = 'Area de rechazo: a la derecha de Zc2 = ')
        pdf.text(x = 120,y = 235, txt = z_critico_superior)
    if(colas == 2):
        pdf.text(x = 30,y = 85, txt = 'Ho: mu >= ')
        pdf.text(x = 53,y = 85,txt = medp)
        pdf.text(x = 30,y = 90, txt = 'Ho: mu < ')
        pdf.text(x = 53,y = 90,txt = medp)
        pdf.text(x = 30,y = 135, txt = 'Paso 4: Regla de decision')
        pdf.image('img/grafica.jpg',x = 40,y = 140,w = 130, h = 80)
        pdf.text(x = 30,y = 225, txt = 'Área de no rechazo: a la izquierda del valor de Zcrítico = ')
        pdf.text(x = 160,y = 225, txt = z_critico_inferior)
        pdf.text(x = 170,y = 225, txt = ',')
        pdf.text(x = 175,y = 225, txt = z_critico_superior)
        pdf.text(x = 180,y = 225, txt = ')')
       # pdf.text(x = 30,y = 230, txt = 'Área de rechazo: a la izquierda de Zc1 = ')
       # pdf.text(x = 120,y = 230, txt = z_critico_inferior)
       # pdf.text(x = 30,y = 235, txt = 'Area de rechazo: a la derecha de Zc2 = ')
       # pdf.text(x = 120,y = 235, txt = z_critico_superior)
        
        print("Salida del if imprimir")
    pdf.text(x = 30,y = 95, txt = 'Paso 2: Nivel de significancia alpha')
    pdf.text(x = 30,y = 100, txt = 'alpha = ')
    pdf.text(x = 47,y = 100, txt = alpha)
    pdf.text(x = 57,y = 100, txt = ' = ')
    pdf.text(x = 63,y = 100, txt = alpha2)
    pdf.text(x = 70,y = 100, txt = '%')
    pdf.text(x = 30,y = 105, txt = 'Paso 3: Estadistico de prueba')
    pdf.image('img/Estadistico_curvanormal.png',x = 30,y = 110,w = 40, h = 20)


    #IMAGEN
    pdf.image('img/logotipo-cunori-transparente.png',x = 27,y = 29,w = 33, h = 33)

    #-------------------------------------------------PAGINA 2------------------------------------------------
    pdf.add_page()
    #RECTA
    pdf.rect(x = 25,y = 25,w = 165,h = 245)
    pdf.text(x = 30,y = 35, txt = 'Paso 5: Prueba del estadistico')
    pdf.image('img/Estadistico_curvanormal.png',x = 30,y = 40,w = 40, h = 20)
    pdf.text(x = 70,y = 50, txt = ' =')
    pdf.text(x = 75,y = 50, txt = '(')
    pdf.text(x = 80,y = 50, txt = mmT)
    pdf.text(x = 90,y = 50, txt = '-')
    pdf.text(x = 95,y = 50, txt = mpT)
    pdf.text(x = 105,y = 50, txt = ')/(')
    pdf.text(x = 110,y = 50, txt = desvestT)
    pdf.text(x = 120,y = 50, txt = '/raiz(')
    pdf.text(x = 135,y = 50, txt = nT)
    pdf.text(x = 140,y = 50, txt = ')) =')
    pdf.text(x = 150,y = 50, txt = zpT)
    if(colas == 1):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = zpT)
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = pvalorT)
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf and zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = zpT)
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 125,y = 185, txt = z_critico_inferior)
            pdf.text(x = 140,y = 185, txt = ',')
            pdf.text(x = 145,y = 185, txt = z_critico_superior)
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = pvalorT)
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = alpha)
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = zpT)
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 130,y = 185, txt = z_critico_inferior)
            pdf.text(x = 145,y = 185, txt = ',')
            pdf.text(x = 150,y = 185, txt = z_critico_superior)
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = pvalorT)
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = alpha)
    if(colas == 2):
        pdf.text(x = 30,y = 65, txt = 'pvalor = 2[0.500 - p(Zp)]')
        pdf.text(x = 30,y = 70, txt = 'pvalor = 2[0.500 - p(')
        pdf.text(x = 75,y = 70, txt = zpT)
        pdf.text(x = 95,y = 70, txt = ')')
        pdf.text(x = 30,y = 75, txt = 'pvalor = ')
        pdf.text(x = 50,y = 75, txt = pvalorT)
        pdf.text(x = 30,y = 170, txt = 'Paso 6: Respuesta')
        if(zp>Zinf and zp<Zsup):
            pdf.text(x = 30,y = 175, txt = '1. No se rechaza la Hipótesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. No se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 142,y = 180, txt = zpT)
            pdf.text(x = 30,y = 185, txt = 'se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 125,y = 185, txt = z_critico_inferior)
            pdf.text(x = 140,y = 185, txt = ',')
            pdf.text(x = 145,y = 185, txt = z_critico_superior)
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. No se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = pvalorT)
            pdf.text(x = 65,y = 195, txt = '> alpha = ')
            pdf.text(x = 90,y = 195, txt = alpha)
        else:
            pdf.text(x = 30,y = 175, txt = '1. Se rechaza la Hipotesis nula H0')
            pdf.text(x = 30,y = 180, txt = '2. Se rechaza la Hipótesis nula H0, ya que Zp = ')
            pdf.text(x = 140,y = 180, txt = zpT)
            pdf.text(x = 30,y = 185, txt = 'no se encuentra entre los valores de Zcrítico (')
            pdf.text(x = 130,y = 185, txt = z_critico_inferior)
            pdf.text(x = 145,y = 185, txt = ',')
            pdf.text(x = 150,y = 185, txt = z_critico_superior)
            pdf.text(x = 160,y = 185, txt = ')')
            pdf.text(x = 30,y = 190, txt = '3. Se rechaza la Hipótesis nula H0, ya que: ')
            pdf.text(x = 30,y = 195, txt = 'pvalor = ')
            pdf.text(x = 50,y = 195, txt = pvalorT)
            pdf.text(x = 65,y = 195, txt = '< alpha = ')
            pdf.text(x = 90,y = 195, txt = alpha)
    pdf.image('img/grafica2.jpg',x = 40,y = 80,w = 130, h = 80)
    pdf.output('hoja.pdf')